package cricketiplanalyser;

public enum SortByField {

      AVERAGE,STRIKE_RATE,MAXIMUM_SIX_AND_FOUR,STRIKING_WITH_MAXIMUM_SIXS_AND_FOURS,AVERAGE_WITH_STRIKE_RATE,
      MAXIMUM_RUNS_WITH_BEST_AVERAGE,BEST_BOWLER_AVERAGE,TOP_BOWLERS_STRIK_RATE,BEST_ECOMONY,BEST_STRIKING_RATE_WITH_5W_AND_4W,
      BEST_BOWLING_AVERAGE_WITH_STRIKE_RATE,MAXIMUM_WICKETS_WITH_BEST_AVERAGE_RATE, BEST_BATTING_BOWLING_AVERAGE,ALL_ROUNDER_PLAYER

}
