package cricketiplanalyser;

public enum SortByField {

      AVERAGE,STRIKE_RATE,MAXIMUM_SIX_AND_FOUR,STRIKING_WITH_MAXIMUM_SIXS_AND_FOURS,AVERAGE_WITH_STRIKE_RATE,
      MAXIMUM_RUNS_WITH_BEST_AVERAGE,TOP_BOWLER_AVERAGE,TOP_BOWLERS_STRIK_RATE
}
